# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupcake',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
